[package]
name = "net"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44", features = [] }
minecraft_protocol = { path = "../minecraft_protocol" }
thiserror = "2.0"
anyhow = "1.0"

[dev-dependencies]
tokio-test = "0.4.4"
