[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
packet_in = { path = "../packet_in" }
packet_out = { path = "../packet_out" }
parse = { path = "../parse" }
packet_id_macro = { path = "../packet_id_macro" }
nbt = { path = "../nbt" }
