[profile.release]
codegen-units = 1
lto = true

[workspace]
resolver = "2"
members = [
    "crates/macros",
    "crates/pico_nbt",
    "crates/minecraft_protocol",
    "crates/packet_serializer",
    "crates/minecraft_packets",
    "crates/net",
    "crates/minecraft_server",
    "binaries/pico_limbo",
    "binaries/pico_ping", "crates/pico_text_component",
]
