[workspace]
resolver = "2"
members = [
    "crates/macros",
    "crates/nbt",
    "crates/minecraft_protocol",
    "crates/packet_serializer",
    "crates/minecraft_packets",
    "crates/net",
    "crates/minecraft_server",
    "binaries/pico_limbo",
    "binaries/pico_wake"
]
