[package]
name = "nbt"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { workspace = true }
thiserror = { workspace = true }
pico_binutils = { path = "../pico_binutils", features = ["binary_writer", "binary_reader", "length_prefixed"] }
