[package]
name = "minecraft_protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
macros = { path = "../macros" }
packet_serializer = { path = "../packet_serializer" }
thiserror = "2.0"
uuid = { version = "1.13", features = ["v4"] }
nbt = { path = "../pico_nbt" }
walkdir = "2.5.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
