[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
macros = { path = "../../macros" }
thiserror = "2.0"
uuid = { version = "1.13", features = ["v4"] }
nbt = { path = "../nbt" }
