[package]
name = "net"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43", features = [] }
minecraft_protocol = { path = "../minecraft_protocol" }
thiserror = "2.0"
anyhow = "1.0"

[dev-dependencies]
tokio-test = "0.4.4"
