[package]
name = "pico_limbo"
version = "1.21.5-5"
edition = "2024"

[dependencies]
tokio = { version = "1.45", features = ["rt", "rt-multi-thread", "macros", "net", "io-util", "time", "sync", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
minecraft_protocol = { path = "../../crates/minecraft_protocol" }
minecraft_packets = { path = "../../crates/minecraft_packets" }
minecraft_server = { path = "../../crates/minecraft_server" }
thiserror = "2.0"
clap = { version = "4.5", features = ["derive"] }
hmac = "0.12.1"
sha2 = "0.10.8"
subtle = "2.6.1"
rand = "0.9.0"
