name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  check:
    name: check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run linter
        run: cargo check

  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: cargo test
