name: Build Linux

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      binary:
        required: true
        type: string


jobs:
  github-releases:
    name: linux
    env:
      platform: linux-x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu --bin pico_limbo --package pico_limbo

      - name: Set file name
        id: set_file_name
        run: |
          echo "file_name=${{ inputs.binary }}_${{ inputs.tag }}_${{ env.platform }}" >> "$GITHUB_OUTPUT"

      - name: Prepare package
        run: |
          mkdir linux
          cp target/x86_64-unknown-linux-gnu/release/${{ inputs.binary }} linux/
          cp -r data/generated linux/assets

      - name: Package as a zip
        working-directory: ./linux
        run: |
          zip --recurse-paths ../${{ steps.set_file_name.outputs.file_name  }}.zip .

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.platform }}
          path: ${{ steps.set_file_name.outputs.file_name  }}.zip
          retention-days: 1
