name: Build MacOS

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      binary:
        required: true
        type: string


jobs:
  build-macos-apple-silicon:
    name: macos_apple_silicon
    env:
      platform: darwin-aarch64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Environment
        # macos 11 was the first version to support ARM
        run: |
          export MACOSX_DEPLOYMENT_TARGET="11"

      - name: Build
        run: |
          cargo build --release --target aarch64-apple-darwin --bin pico_limbo --package pico_limbo

      - name: Set file name
        id: set_file_name
        run: |
          echo "file_name=${{ inputs.binary }}_${{ inputs.tag }}_${{ env.platform }}" >> "$GITHUB_OUTPUT"

      - name: Prepare Package
        run: |
          mkdir darwin-aarch64
          cp target/aarch64-apple-darwin/release/${{ inputs.binary }} darwin-aarch64/
          cp -r data/generated darwin-aarch64/assets

      - name: Package as a zip
        working-directory: ./darwin-aarch64
        run: |
          zip -r ../${{ steps.set_file_name.outputs.file_name }}.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.platform }}
          path: ${{ steps.set_file_name.outputs.file_name }}.zip
          retention-days: 1
