name: Build and Publish Docker Images

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write
  attestations: write

jobs:
  build-standalone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for standalone image
        id: meta-standalone
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push standalone image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta-standalone.outputs.tags }}
          labels: ${{ steps.meta-standalone.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-pterodactyl-pico-limbo:
    if: github.ref == 'refs/heads/master'
    needs: build-standalone
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for pterodactyl image
        id: meta-pterodactyl
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=pterodactyl-pico-limbo

      - name: Build and push pterodactyl image
        uses: docker/build-push-action@v6
        with:
          context: pterodactyl/yolks/pico_limbo
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta-pterodactyl.outputs.tags }}
          labels: ${{ steps.meta-pterodactyl.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-pterodactyl-pico-wake:
    if: github.ref == 'refs/heads/master'
    needs: build-standalone
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 21
          - 17

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for pterodactyl image
        id: meta-pterodactyl
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=pterodactyl-pico-wake-${{ matrix.tag }}

      - name: Build and push pterodactyl image
        uses: docker/build-push-action@v6
        with:
          context: pterodactyl/yolks/pico_wake
          file: pterodactyl/yolks/pico_wake/${{ matrix.tag }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta-pterodactyl.outputs.tags }}
          labels: ${{ steps.meta-pterodactyl.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
