name: Release

# Configure your build and release platforms
env:
  # If your repo name differs from your binary name, change it.
  # Check you Cargo.toml -> package -> name
  binary: pico_limbo

permissions:
  # To upload files to GitHub Releases
  contents: write
  # To verify the deployment originates from an appropriate source
  id-token: write

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Add tag version: (e.g. -> v3.6.1)"
        required: true
        type: string

jobs:
  # Load variables
  load-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    outputs:
      tag: ${{ ( inputs.tag || github.ref_name ) }}
      binary: ${{ env.binary }}

  # Build for Linux x86_64
  build-linux:
    needs: load-env
    uses: ./.github/workflows/linux.yaml
    name: build
    with:
      tag: ${{ needs.load-env.outputs.tag }}
      binary: ${{ needs.load-env.outputs.binary }}

  # Build for Windows x86_64
  build-windows:
    needs: load-env
    uses: ./.github/workflows/windows.yaml
    name: build
    with:
      tag: ${{ needs.load-env.outputs.tag }}
      binary: ${{ needs.load-env.outputs.binary }}


  # Build for MacOS x86_64/ARM64
  build-macos:
    needs: load-env
    uses: ./.github/workflows/macos.yaml
    name: build
    with:
      tag: ${{ needs.load-env.outputs.tag }}
      binary: ${{ needs.load-env.outputs.binary }}


  # Release binaries in GitHub
  publish-github-releases:
    needs:
      - load-env
      - build-linux
      - build-windows
      - build-macos
    if: ${{ always() && !failure() && !cancelled() }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact_name: linux-gnu-x86_64
            os: ubuntu-latest
          - artifact_name: linux-musl-x86_64
            os: ubuntu-latest
          - artifact_name: windows-x86_64
            os: windows-latest
          - artifact_name: darwin-x86_64
            os: macos-latest
          - artifact_name: darwin-aarch64
            os: macos-latest
    uses: ./.github/workflows/github_releases.yaml
    name: publish / github-releases
    with:
      tag: ${{ needs.load-env.outputs.tag }}
      os: ${{ matrix.os }}
      artifact_name: ${{ matrix.artifact_name }}
    secrets: inherit
